[build]
  publish = "public"

[[redirects]]
  from = "/api"
  to = "https://ggucapi.giri-kailasam.workers.dev/"
  status = 200
  force = true

[[redirects]]
  from = "/adminapi"
  to = "https://ggucadmin.giri-kailasam.workers.dev/"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
